# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://et-cetera.ru/mobile/
      name: Et-cetera.ru
    - url: https://site.for.check.error
      name: Error.site
  morphology:
    status: "false" #'true' or 'false' - enable or disable morphology
    active-threads: 7

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: word
    password: word
    hikari:
      schema: storage
      maximum-pool-size: 10