# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

init:
  morphology: YES #or NO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: word
    password: word
    hikari:
      schema: storage